[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

[window.dimensions]
columns = 130
lines = 40

[font]
normal.family = "MesloLGS Nerd Font Mono"   
size = 16.0  

[cursor.style]
shape = "Beam"


